version: '3.7'

services:
  mediscreen-container:
    image: oc-mediscreen:4
    build:
      context: ./
      dockerfile: DockerFile
    depends_on:
      - mysql_db
    volumes:
      - /data/mediscreen
    ports:
      - "8080:8080"
    links:
      - mysql_db:app_db

  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_USER: user
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN