version: '3.7'

services:
  assess_service:
    depends_on:
      - mongo_db
      - mysql_db
    image: oc-assess
    build:
      context: ./assess-back
      dockerfile: DockerFileAssess
    ports:
      - "8083:8083"
    links:
      - mongo_db:mongo_db
      - mysql_db:mysql_db

  note_service:
    image: oc-notes
    build:
      context: ./notes-back
      dockerfile: DockerFileNote
    depends_on:
      - mongo_db
    ports:
      - "8084:8084"
    links:
      - mongo_db:app_db

  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_USER: user
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN

  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017

  mediscreen-container:
    image: oc-mediscreen:4
    build:
      context: ./
      dockerfile: DockerFile
    depends_on:
      - mysql_db
      - note_service
      - assess_service
    volumes:
      - /data/mediscreen
    ports:
      - "8081:8081"
    links:
      - mysql_db:app_db
      - note_service:app_notes
      - assess_service:app_assess
