version: '3.7'

services:
  mediscreen-container:
    image: oc-mediscreen:4
    build:
      context: ./
      dockerfile: DockerFile
    depends_on:
      - mysql_db
      - oc-notes
    volumes:
      - /data/mediscreen
    ports:
      - "8080:8080"
    links:
      - mysql_db:app_db
      - oc-notes:app_notes

  note_service:
    image: oc-notes
    build:
      dockerfile: DockerFileNote
    depends_on:
      - mongo_db
    ports:
      - "8080:8080"
    links:
      - mongo_db:app_db

  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_USER: user
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN

  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017