POST http://localhost:8081/api/patient
Content-Type: application/json

{
  "firstName": "Ferguson",
  "name": "Lucas",
  "dob": "1968-06-22",
  "sex": "M",
  "address": "2 Warren Street",
  "phone": "387-866-1399"
}

###
POST http://localhost:8081/api/patient
Content-Type: application/json

{
  "firstName": "Rees",
  "name": "Pippa",
  "dob": "1952-09-27",
  "sex": "F",
  "address": "745 West Valley Farms Drive",
  "phone": "628-423-0993"
}

###
POST http://localhost:8081/api/patient
Content-Type: application/json

{
  "firstName": "Arnold",
  "name": "Edward",
  "dob": "1952-11-11",
  "sex": "M",
  "address": "599 East Garden Ave",
  "phone": "123-727-2779"
}

###
POST http://localhost:8081/api/patient
Content-Type: application/json

{
  "firstName": "Sharp",
  "name": "Anthony",
  "dob": "1946-11-26",
  "sex": "M",
  "address": "894 Hall Street",
  "phone": "451-761-8383"
}

###
POST http://localhost:8081/api/patient
Content-Type: application/json

{
  "firstName": "Ince",
  "name": "Wendy",
  "dob": "1958-06-29",
  "sex": "F",
  "address": "4 Southampton Road",
  "phone": "802-911-9975"
}

###
POST http://localhost:8081/api/patient
Content-Type: application/json

{
  "firstName": "Wilson",
  "name": "Claire",
  "dob": "1966-12-31",
  "sex": "F",
  "address": "12 Cobblestone St",
  "phone": "300-452-1091"
}

###
POST http://localhost:8081/api/patient
Content-Type: application/json

{
  "firstName": "Buckland",
  "name": "Max",
  "dob": "1945-06-24",
  "sex": "M",
  "address": "193 Vale St ",
  "phone": "833-534-0864"
}


###
POST http://localhost:8081/api/patient
Content-Type: application/json

{
  "firstName": "Clark",
  "name": "Natalie",
  "dob": "1964-06-18",
  "sex": "F",
  "address": "12 Beechwood Road",
  "phone": "241-467-9197"
}


###
POST http://localhost:8081/api/patient
Content-Type: application/json

{
  "firstName": "Bailey",
  "name": "Piers",
  "dob": "1959-06-28",
  "sex": "M",
  "address": "1202 Bumble Dr",
  "phone": "747-815-0557"
}



### Ferguson 9
POST http://localhost:8081/api/patient/9/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il « se sent très bien »\n Poids égal ou inférieur au poids recommandé"
}

###
POST http://localhost:8081/api/patient/9/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il se sent fatigué pendant la journée\nIl se plaint également de douleurs musculaires\nTests de laboratoire indiquant une microalbumine élevée"
}

###
POST http://localhost:8081/api/patient/9/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il ne se sent pas si fatigué que ça\nFumeur, il a arrêté dans les 12 mois précédents\nTests de laboratoire indiquant que les anticorps sont élevés"
}


###Rees -10
POST http://localhost:8081/api/patient/10/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il ressent beaucoup de stress au travail\nIl se plaint également que son audition est anormale dernièremen"
}

###Rees -10
POST http://localhost:8081/api/patient/10/note
Content-Type: application/json

{
  "note": "Le patient déclare avoir fait une réaction aux médicaments au cours des 3 derniers mois\nIl remarque également que son audition continue d'être anormale"
}

###Rees -10
POST http://localhost:8081/api/patient/10/note
Content-Type: application/json

{
  "note": "Tests de laboratoire indiquant une microalbumine élevée"
}

###Rees -10
POST http://localhost:8081/api/patient/10/note
Content-Type: application/json

{
  "note": "Le patient déclare que tout semble aller bien\n Le laboratoire rapporte que l'hémoglobine A1C dépasse le niveau recommandé\n Le patient déclare qu’il fume depuis longtemps"
}

###Arnold -11
POST http://localhost:8081/api/patient/11/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il fume depuis peu"
}


###Arnold -11
POST http://localhost:8081/api/patient/11/note
Content-Type: application/json

{
  "note": "Tests de laboratoire indiquant une microalbumine élevée"
}


###Arnold -11
POST http://localhost:8081/api/patient/11/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il est fumeur et qu'il a cessé de fumer l'année dernière\nIl se plaint également de crises d’apnée respiratoire anormales\nTests de laboratoire indiquant un taux de cholestérol LDL élevé"
}

###Arnold -11
POST http://localhost:8081/api/patient/11/note
Content-Type: application/json

{
  "note": "Tests de laboratoire indiquant un taux de cholestérol LDL élevé"
}


###Sharp -12
POST http://localhost:8081/api/patient/12/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il lui est devenu difficile de monter les escaliers\n Il se plaint également d’être essoufflé\nTests de laboratoire indiquant que les anticorps sont élevés\nRéaction aux médicaments"
}

###Sharp -12
POST http://localhost:8081/api/patient/12/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il a mal au dos lorsqu'il reste assis pendant longtemps"
}

###Sharp -12
POST http://localhost:8081/api/patient/12/note
Content-Type: application/json

{
  "note": "Le patient déclare avoir commencé à fumer depuis peu\n Hémoglobine A1C supérieure au niveau recommandé"
}

###Ince -13
POST http://localhost:8081/api/patient/13/note
Content-Type: application/json

{
  "note": "Le patient déclare avoir des douleurs au cou occasionnellement\nLe patient remarque également que certains aliments ont un goût différent\nRéaction apparente aux médicaments\nPoids corporel supérieur au poids recommandé"
}

###Ince -13
POST http://localhost:8081/api/patient/13/note
Content-Type: application/json

{
  "note": "Le patient déclare avoir eu plusieurs épisodes de vertige depuis la dernière visite.\nTaille incluse dans la fourchette concernée"
}

###Ince -13
POST http://localhost:8081/api/patient/13/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il souffre encore de douleurs cervicales occasionnelles\nTests de laboratoire indiquant une microalbumine élevée\nFumeur, il a arrêté dans les 12 mois précédents"
}

###Ince -13
POST http://localhost:8081/api/patient/13/note
Content-Type: application/json

{
  "note": "Le patient déclare avoir eu plusieurs épisodes de vertige depuis la dernière visite.\n Tests de laboratoire indiquant que les anticorps sont élevés"
}



###Ross -14
POST http://localhost:8081/api/patient/14/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il se sent bien\nPoids corporel supérieur au poids recommandé"
}


###Ross -14
POST http://localhost:8081/api/patient/14/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il se sent bien"
}



###Wilson -15
POST http://localhost:8081/api/patient/15/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il se réveille souvent avec une raideur articulaire\nIl se plaint également de difficultés pour s’endormir\nPoids corporel supérieur au poids recommandé\nTests de laboratoire indiquant un taux de cholestérol LDL élevé"
}



###Buckland -16
POST http://localhost:8081/api/patient/16/note
Content-Type: application/json

{
  "note": "Les tests de laboratoire indiquent que les anticorps sont élevés\nHémoglobine A1C supérieure au niveau recommandé"
}


###Clark -17
POST http://localhost:8081/api/patient/17/note
Content-Type: application/json

{
  "note": "Le patient déclare avoir de la difficulté à se concentrer sur ses devoirs scolaires\nHémoglobine A1C supérieure au niveau recommandé"
}


###Clark -17
POST http://localhost:8081/api/patient/17/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il s’impatiente facilement en cas d’attente prolongée\nIl signale également que les produits du distributeur automatique ne sont pas bons\nTests de laboratoire signalant des taux anormaux de cellules sanguines"
}

###Clark -17
POST http://localhost:8081/api/patient/17/note
Content-Type: application/json

{
  "note": "Le patient signale qu'il est facilement irrité par des broutilles\n Il déclare également que l'aspirateur des voisins fait trop de bruit\n Tests de laboratoire indiquant que les anticorps sont élevés"
}


###Bailey -18
POST http://localhost:8081/api/patient/18/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il n'a aucun problème"
}


###Bailey -18
POST http://localhost:8081/api/patient/18/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il n'a aucun problème\nTaille incluse dans la fourchette concernée\nHémoglobine A1C supérieure au niveau recommandé"
}

###Bailey -18
POST http://localhost:8081/api/patient/18/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il n'a aucun problème\nPoids corporel supérieur au poids recommandé\nLe patient a signalé plusieurs épisodes de vertige depuis sa dernière visite"
}

###Bailey -18
POST http://localhost:8081/api/patient/18/note
Content-Type: application/json

{
  "note": "Le patient déclare qu'il n'a aucun problème\n  Tests de laboratoire indiquant une microalbumine élevée"
}




